# Test workflow with GitHub secrets
name: Deploy to Staging

on:
  push:
    branches-ignore:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: readaoke-staging
  REGION: us-central1

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    environment: staging

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ''
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build and Push Container
        run: |-
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/readaoke-staging:${{ github.sha }} .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/readaoke-staging:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy readaoke-staging \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/readaoke-staging:${{ github.sha }} \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars="ENVIRONMENT=staging"
