name: Staging Deployment

on:
  push:
    branches-ignore:
      - main

env:
  PROJECT_ID: readin-444609
  SERVICE_NAME: readaoke-staging
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - id: auth
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
      
      - name: 'Deploy to Cloud Run'
        run: |-
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --source . \
            --project ${{ env.PROJECT_ID }} \
            --region ${{ env.REGION }} \
            --allow-unauthenticated
