name: Staging Deployment

on:
  push:
    branches-ignore:
      - main

env:
  PROJECT_ID: readin-444609
  SERVICE_NAME: readaoke-staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v4
      
      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/232757409674/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider'
          service_account: 'github-actions@readin-444609.iam.gserviceaccount.com'
          
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      
      - name: Build and Deploy
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --source . \
            --project ${{ env.PROJECT_ID }} \
            --region us-central1 \
            --allow-unauthenticated
