name: Staging Deployment

on:
  push:
    branches-ignore:
      - main

env:
  PROJECT_ID: readin-444609
  SERVICE_NAME: readaoke-staging
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup gcloud CLI
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > gcp-key.json
          gcloud auth activate-service-account --key-file=gcp-key.json
          gcloud config set project ${{ env.PROJECT_ID }}
          
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --source . \
            --region ${{ env.REGION }} \
            --allow-unauthenticated
